# Generated by Django 4.2.5 on 2023-10-03 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(5), django.core.validators.MinLengthValidator(5)])),
                ('name', models.CharField(max_length=255)),
                ('no_of_guests', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(6), django.core.validators.MinLengthValidator(1)])),
                ('booking_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(11), django.core.validators.MinLengthValidator(11)])),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inventory', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(5), django.core.validators.MinLengthValidator(1)])),
            ],
        ),
    ]
